# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Documents/merge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Documents/merge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/merge/CMakeFiles /home/pi/Documents/merge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/merge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Distance_Meter-2.0.out

# Build rule for target.
Distance_Meter-2.0.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Distance_Meter-2.0.out
.PHONY : Distance_Meter-2.0.out

# fast build rule for target.
Distance_Meter-2.0.out/fast:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/build
.PHONY : Distance_Meter-2.0.out/fast

# target to build an object file
MPU9255.o:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/MPU9255.o
.PHONY : MPU9255.o

# target to preprocess a source file
MPU9255.i:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/MPU9255.i
.PHONY : MPU9255.i

# target to generate assembly for a file
MPU9255.s:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/MPU9255.s
.PHONY : MPU9255.s

# target to build an object file
i2c_device.o:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/i2c_device.o
.PHONY : i2c_device.o

# target to preprocess a source file
i2c_device.i:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/i2c_device.i
.PHONY : i2c_device.i

# target to generate assembly for a file
i2c_device.s:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/i2c_device.s
.PHONY : i2c_device.s

# target to build an object file
laser.o:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/laser.o
.PHONY : laser.o

# target to preprocess a source file
laser.i:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/laser.i
.PHONY : laser.i

# target to generate assembly for a file
laser.s:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/laser.s
.PHONY : laser.s

# target to build an object file
merge_main.o:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/merge_main.o
.PHONY : merge_main.o

# target to preprocess a source file
merge_main.i:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/merge_main.i
.PHONY : merge_main.i

# target to generate assembly for a file
merge_main.s:
	$(MAKE) -f CMakeFiles/Distance_Meter-2.0.out.dir/build.make CMakeFiles/Distance_Meter-2.0.out.dir/merge_main.s
.PHONY : merge_main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Distance_Meter-2.0.out"
	@echo "... MPU9255.o"
	@echo "... MPU9255.i"
	@echo "... MPU9255.s"
	@echo "... i2c_device.o"
	@echo "... i2c_device.i"
	@echo "... i2c_device.s"
	@echo "... laser.o"
	@echo "... laser.i"
	@echo "... laser.s"
	@echo "... merge_main.o"
	@echo "... merge_main.i"
	@echo "... merge_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

